try get and store double input kind, as file, as yaml object

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,8 +15,8 @@ inputs:
     description: 'Should be removed the labels previously assigned that don''t present a reference in the current conventional commits.'
     required: false
     default: 'true'
-  conventional-commits-file:
-    description: 'YAML file that contains a list with conventional commits and the labels matching that must be assigned'
+  conventional-commits:
+    description: 'YAML object or YAML file that contains a list with conventional commits and the labels matching that must be assigned'
     required: false
     default: 'conventional-commits.yml'
   not-apply-changes:
@@ -44,24 +44,65 @@ runs:
       shell: bash
       run: |
         #!/bin/sh
-        echo "ACTION_STATUS=STARTING" >> $GITHUB_ENV
+        echo "ACTION_STATUS=VALIDATE" >> $GITHUB_ENV
         echo "ACTION_MESSAGE=" >> $GITHUB_ENV
 
         # Change to job working directory
         cd ${{ github.action_path }}
 
-        # Validate exists resource
-        if [[ ! -f "${{ inputs.conventional-commits-file }}" ]]; then
-          echo "ACTION_STATUS=START_FAILED" >> $GITHUB_ENV;
-          echo "ACTION_MESSAGE=Conventional commits file not founded at ${{ inputs.conventional-commits-file }}" >> $GITHUB_ENV;
-          exit 1;
+        INPUT_CONVENTIONAL_COMMITS=$(cat << EOF
+        ${{ inputs.conventional-commits }}
+        EOF
+        )
+
+        # Generate a temporal folder
+        TMP_FOLDER=$(mktemp -dq ./XXXXXXXX)
+        if [ $? -ne 0 ]; then
+            echo "ACTION_STATUS=FAILED" >> $GITHUB_ENV;
+            echo "ACTION_MESSAGE=can't create temp file: $0" >> $GITHUB_ENV;
+            exit 1;
+        fi
+        echo "TMP_FOLDER=$TMP_FOLDER" >> $GITHUB_ENV
+
+        # Validate input and store in temporally file yml
+        # Check the input is a valid path
+        if [[ $INPUT_CONVENTIONAL_COMMITS =~ ^([\.\/]?.*)?(\/.*)?\.((yml)|(yaml))$  ]]; then
+
+          # Validate exists resource
+          if [[ ! -f "$INPUT_CONVENTIONAL_COMMITS" ]]; then
+            echo "ACTION_STATUS=FAILED" >> $GITHUB_ENV;
+            echo "ACTION_MESSAGE=conventional commits file not founded at $INPUT_CONVENTIONAL_COMMITS" >> $GITHUB_ENV;
+            exit 1;
+          fi;
+
+          # store temporally conventional-commits file
+          cp "$INPUT_CONVENTIONAL_COMMITS" $TMP_FOLDER/conventional-commits.yml;
+          
+        else
+
+        # store temporally conventional-commits file
+        cat > $TMP_FOLDER/conventional-commits.yml <<EOF
+        ${{ inputs.conventional-commits }}
+        EOF
+
         fi
 
         # Store token in env to easy the Github CLI authorization
         echo "GITHUB_TOKEN=${{ inputs.github-token }}" >> $GITHUB_ENV
 
-        echo "ACTION_STATUS=STARTED" >> $GITHUB_ENV
+    - name: Parse YAML
+      id: parse-yaml
+      shell: bash
+      run: |
+        echo "ACTION_STATUS=PARSE" >> $GITHUB_ENV
         echo "ACTION_MESSAGE=" >> $GITHUB_ENV
+
+        python3 -c "import sys, yaml, json; print(json.dumps(yaml.safe_load(open('$TMP_FOLDER/conventional-commits.yml')), indent=2, sort_keys=False))" >> $TMP_FOLDER/conventional-commits.json
+        if [ $? -ne 0 ]; then
+            echo "ACTION_STATUS=FAILED" >> $GITHUB_ENV;
+            echo "ACTION_MESSAGE=failed to validate conventional-commits file: $0" >> $GITHUB_ENV;
+            exit 1;
+        fi
 
     - name: End
       id: end
@@ -69,6 +110,10 @@ runs:
       run: |
         echo "ACTION_STATUS=ENDING" >> $GITHUB_ENV
         echo "ACTION_MESSAGE=" >> $GITHUB_ENV
+
+        echo "testing:start"
+        echo "$CONVENTIONAL_COMMITS"
+        echo "testing:end"
 
         echo "LABELS_ASSIGNED=" >> $GITHUB_ENV
         echo "LABELS_REMOVED=" >> $GITHUB_ENV
